export const radioColorMap = {
    primary: `ck-bg-primary ck-text-white`,
    secondary: `ck-bg-secondary ck-text-white`,
    tertiary: 'ck-bg-secondary hover:ck-bg-primary ck-text-white',
    quaternary: 'ck-bg-transparent hover:ck-text-primary',
    danger: 'ck-bg-red-500 hover:ck-bg-red-600 ck-text-white',
    neutral: 'ck-bg-base-200 hover:ck-bg-base-300',
    success: 'ck-bg-green-500 hover:ck-bg-green-600 ck-text-white',
    error: 'ck-bg-red-500 hover:ck-bg-red-600 ck-text-white',
    warning: 'ck-bg-orange-500 hover:ck-bg-orange-600 ck-text-white',
    info: 'ck-bg-blue-500 hover:ck-bg-blue-600 ck-text-white',
    light: 'ck-bg-gray-100 hover:ck-bg-gray-200 ck-text-gray-800',
    dark: 'ck-bg-gray-800 hover:ck-bg-gray-900 ck-text-white',
    none: '',
};
