export const radioColorMap = {
    primary: `bpl-bg-primary bpl-text-white`,
    secondary: `bpl-bg-secondary bpl-text-white`,
    tertiary: "bpl-bg-secondary hover:bpl-bg-primary bpl-text-white",
    quaternary: "bpl-bg-transparent hover:bpl-text-primary",
    danger: "bpl-bg-red-500 hover:bpl-bg-red-600 bpl-text-white",
    neutral: "bpl-bg-base-200 hover:bpl-bg-base-300",
    success: "bpl-bg-green-500 hover:bpl-bg-green-600 bpl-text-white",
    error: "bpl-bg-red-500 hover:bpl-bg-red-600 bpl-text-white",
    warning: "bpl-bg-orange-500 hover:bpl-bg-orange-600 bpl-text-white",
    info: "bpl-bg-blue-500 hover:bpl-bg-blue-600 bpl-text-white",
    light: "bpl-bg-gray-100 hover:bpl-bg-gray-200 bpl-text-gray-800",
    dark: "bpl-bg-gray-800 hover:bpl-bg-gray-900 bpl-text-white",
    none: "",
};
